-- Generated by scripts/generate-seed-sql.js — do not hand-edit, regenerate instead.
-- Run once in the Supabase SQL editor, after 002_gyms_and_accounts.sql.

-- ─────────────────────────── Demo gyms (fictional showcase data) ───────────────────────────

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '1', 'Budapest Karate Akadémia', '{"Karate"}', 'Andrássy út 45, Budapest, 1061',
  47.5051, 19.0634, 'One of Budapest''s premier karate academies, offering training for all ages and skill levels in traditional Shotokan and sport karate.', 'https://example.com/bka',
  '{"beginner-friendly","kids-classes","friendly-community"}', 'No prior experience required. Just show up in comfortable sportswear — we''ll take care of the rest.', 'Comfortable sportswear. Karate gi available to borrow for the first class.',
  'low', '[{"day":"Monday","time":"17:30"},{"day":"Wednesday","time":"17:30"},{"day":"Friday","time":"18:00"},{"day":"Saturday","time":"10:00"}]'::jsonb, 6,
  '+36 70 888 2267', 'budapestkarateakademia@example.com', 'https://facebook.com/budapestkarateakademia', 'https://instagram.com/budapestkarateakademia',
  11000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('1', 'hu', 'Az egyik legjobb budapesti karate akadémia, minden korosztálynak és szinten, hagyományos Shotokan és sportkarate oktatással.', 'Nincs szükség előzetes tapasztalatra. Gyere kényelmes sportruhában — a többiről mi gondoskodunk.', 'Kényelmes sportruházat. Karate gi kölcsönözhető az első órára.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '2', 'Fight Club Budapest', '{"MMA","BJJ","Boxing"}', 'Váci út 110, Budapest, 1133',
  47.5289, 19.0521, 'A top-tier MMA gym with professional coaches in BJJ, boxing, and mixed martial arts. Home to several Hungarian national champions.', 'https://example.com/fcb',
  '{"hard-training","competition-team","professional-coaches"}', 'First session is a technique-only introduction — no sparring. Coach evaluates before any contact training.', 'Mouthguard and groin guard required from session 2. Gloves available to borrow on your first visit.',
  'high', '[{"day":"Monday","time":"19:00"},{"day":"Tuesday","time":"19:00"},{"day":"Thursday","time":"19:00"},{"day":"Saturday","time":"11:00"}]'::jsonb, 13,
  '+36 20 172 1424', 'fightclubbudapest@example.com', 'https://facebook.com/fightclubbudapest', 'https://instagram.com/fightclubbudapest',
  22000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('2', 'hu', 'Csúcskategóriás MMA terem profi edzőkkel BJJ-ben, bokszban és kevert harcművészetekben. Több magyar bajnok otthona.', 'Az első alkalom csak technika, nincs sparring. Az edző mérlegel, mielőtt bármilyen kontaktos edzés kezdődne.', 'Fogvédő és ágyékvédő a 2. alkalomtól kötelező. Kesztyű kölcsönözhető az első látogatáskor.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '3', 'Muay Thai Budapest', '{"Muay Thai"}', 'Üllői út 22, Budapest, 1085',
  47.4913, 19.0668, 'The leading Muay Thai gym in Hungary, with certified instructors trained in Thailand. Classes for beginners through advanced fighters.', 'https://example.com/mtb',
  '{"beginner-friendly","friendly-community","professional-coaches"}', 'First class is fitness + basic technique only, zero contact. You''ll leave sweaty and smiling.', 'Sports clothes and boxing wraps. Gloves available to borrow for the first few sessions.',
  'medium', '[{"day":"Monday","time":"18:00"},{"day":"Wednesday","time":"18:00"},{"day":"Friday","time":"18:00"}]'::jsonb, 8,
  '+36 20 282 9809', 'muaythaibudapest@example.com', 'https://facebook.com/muaythaibudapest', 'https://instagram.com/muaythaibudapest',
  15000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('3', 'hu', 'Magyarország vezető thai box terme, Thaiföldön képzett, minősített oktatókkal. Kezdőtől a haladó versenyzőkig mindenkinek.', 'Az első óra csak kondi és alaptechnika, nulla kontakttal. Izzadtan, de mosolyogva távozol.', 'Sportruha és bokszpólya. Kesztyű kölcsönözhető az első pár alkalomra.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '4', 'BJJ Factory Budapest', '{"BJJ"}', 'Bartók Béla út 36, Budapest, 1114',
  47.4738, 19.0434, 'Dedicated Brazilian Jiu-Jitsu academy affiliated with a Gracie-certified school. Open mat sessions every weekend.', 'https://example.com/bjjf',
  '{"beginner-friendly","open-mat","friendly-community"}', 'Absolute beginners welcome. We run a dedicated Fundamentals class every Monday — perfect starting point.', 'Comfortable clothes for the first class. BJJ gi loaner available. Rash guard recommended from week 2.',
  'medium', '[{"day":"Monday","time":"18:30"},{"day":"Tuesday","time":"20:00"},{"day":"Thursday","time":"18:30"},{"day":"Saturday","time":"11:00"},{"day":"Sunday","time":"11:00"}]'::jsonb, 11,
  '+36 20 376 6474', 'bjjfactorybudapest@example.com', 'https://facebook.com/bjjfactorybudapest', 'https://instagram.com/bjjfactorybudapest',
  17000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('4', 'hu', 'Kizárólag brazil jiu-jitsura specializálódott akadémia, Gracie-minősítésű iskolával affiliálva. Minden hétvégén open mat.', 'Teljesen kezdők is szívesen látottak. Minden hétfőn külön Alapok órát tartunk — tökéletes belépő pont.', 'Kényelmes ruha az első órára. Kölcsönözhető BJJ gi. Rash guard ajánlott a 2. héttől.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '5', 'Budokan Martial Arts Center', '{"Karate","MMA"}', 'Margit körút 15, Budapest, 1027',
  47.5072, 19.0356, 'A large martial arts complex combining traditional Karate with modern MMA training. Features a dedicated ring and mat area.', 'https://example.com/budokan',
  '{"kids-classes","beginner-friendly","friendly-community"}', 'Trial class is completely free. Children''s classes run parallel to adult sessions so families can train together.', 'Comfortable sports clothes. All equipment provided during the trial period.',
  'medium', '[{"day":"Tuesday","time":"17:00"},{"day":"Thursday","time":"17:00"},{"day":"Saturday","time":"09:00"}]'::jsonb, 2,
  '+36 20 293 2575', 'budokanmartialartscenter@example.com', 'https://facebook.com/budokanmartialartscenter', 'https://instagram.com/budokanmartialartscenter',
  15500, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('5', 'hu', 'Nagy harcművészeti komplexum, amely ötvözi a hagyományos karatét a modern MMA edzéssel. Saját ringgel és szőnyegterülettel.', 'A próbaóra teljesen ingyenes. A gyerekfoglalkozások a felnőtt órákkal párhuzamosan futnak, így a család együtt edzhet.', 'Kényelmes sportruha. Minden felszerelést biztosítunk a próbaidőszak alatt.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '6', 'Iron Fist Boxing Gym', '{"Boxing"}', 'Kálvin tér 5, Budapest, 1091',
  47.4909, 19.0601, 'Classic boxing gym in central Budapest with a rich history. Offers amateur and professional boxing training programs.', 'https://example.com/ironfist',
  '{"hard-training","competition-team","professional-coaches"}', 'First class is pad work and bag work only — no sparring. Coach approval required before any contact.', 'Hand wraps and boxing gloves (available to purchase or rent on site).',
  'high', '[{"day":"Monday","time":"18:00"},{"day":"Tuesday","time":"18:00"},{"day":"Wednesday","time":"18:00"},{"day":"Thursday","time":"18:00"},{"day":"Friday","time":"18:00"},{"day":"Saturday","time":"10:00"}]'::jsonb, 9,
  '+36 70 976 9797', 'ironfistboxinggym@example.com', 'https://facebook.com/ironfistboxinggym', 'https://instagram.com/ironfistboxinggym',
  18500, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('6', 'hu', 'Klasszikus bokszterem a belvárosban, gazdag történelemmel. Amatőr és profi bokszedzési programokat is kínál.', 'Az első óra csak lapp- és zsákmunka — sparring nincs. Kontaktos edzés csak edzői jóváhagyással.', 'Kéztekercs és bokszkesztyű (helyben vásárolható vagy bérelhető).', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '7', 'Tiger Muay Thai & BJJ Budapest', '{"Muay Thai","BJJ"}', 'Rákóczi út 62, Budapest, 1074',
  47.4985, 19.0721, 'An affiliate of the world-famous Tiger Muay Thai camp in Phuket. Offers Muay Thai and Brazilian Jiu-Jitsu under expert guidance.', 'https://example.com/tiger',
  '{"professional-coaches","competition-team","open-mat"}', 'First two sessions are technique-only. Sparring begins only after coach assessment — your safety is our priority.', 'Shorts and rash guard for BJJ. Boxing wraps and mouthguard for Muay Thai.',
  'high', '[{"day":"Monday","time":"18:30"},{"day":"Wednesday","time":"18:30"},{"day":"Friday","time":"18:30"},{"day":"Saturday","time":"10:00"}]'::jsonb, 7,
  '+36 30 445 8823', 'tigermuaythaibjjbudapest@example.com', 'https://facebook.com/tigermuaythaibjjbudapest', 'https://instagram.com/tigermuaythaibjjbudapest',
  20000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('7', 'hu', 'A világhírű phuketi Tiger Muay Thai tábor magyarországi affiliáltja. Thai boksz és brazil jiu-jitsu szakértő vezetéssel.', 'Az első két alkalom csak technika. Sparring csak edzői felmérés után — a biztonságod a legfontosabb.', 'Rövidnadrág és rash guard BJJ-hez. Bokszpólya és fogvédő thai bokszhoz.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '8', 'Warriors MMA Club', '{"MMA","Boxing","Muay Thai"}', 'Fehér út 10, Budapest, 1149',
  47.5087, 19.1143, 'A well-rounded MMA facility offering boxing, Muay Thai, and mixed martial arts coaching. Hosts regular sparring events.', 'https://example.com/warriors',
  '{"friendly-community","beginner-friendly","open-mat"}', 'We welcome complete beginners. Separate beginner classes run before main sessions — no experience needed.', 'Sports clothes for the first class. Full gear list provided after your first session.',
  'medium', '[{"day":"Monday","time":"19:00"},{"day":"Wednesday","time":"19:00"},{"day":"Friday","time":"19:00"},{"day":"Saturday","time":"10:00"}]'::jsonb, 14,
  '+36 30 599 6191', 'warriorsmmaclub@example.com', 'https://facebook.com/warriorsmmaclub', 'https://instagram.com/warriorsmmaclub',
  16500, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('8', 'hu', 'Sokoldalú MMA létesítmény bokszal, thai boksszal és kevert harcművészet oktatással. Rendszeres sparring eseményeket tart.', 'Teljesen kezdőket is szívesen látunk. A fő órák előtt külön kezdő csoport indul — előzetes tapasztalat nem szükséges.', 'Sportruha az első órára. Az első alkalom után teljes felszereléslista.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '9', 'Kyokushin Budapest', '{"Karate"}', 'Gellért tér 3, Budapest, 1114',
  47.4868, 19.0487, 'Specializing in Kyokushin full-contact karate, this dojo develops discipline, strength, and fighting spirit.', 'https://example.com/kyokushin',
  '{"hard-training","competition-team","professional-coaches"}', 'Kyokushin is full-contact, but your first class is conditioning + basics only — absolutely zero contact.', 'Karate gi or comfortable sports clothes for the first session.',
  'high', '[{"day":"Tuesday","time":"18:00"},{"day":"Thursday","time":"18:00"},{"day":"Saturday","time":"10:00"}]'::jsonb, 11,
  '+36 70 899 0901', 'kyokushinbudapest@example.com', 'https://facebook.com/kyokushinbudapest', 'https://instagram.com/kyokushinbudapest',
  18000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('9', 'hu', 'Kyokushin teljes kontaktos karatéra specializálódott dojo, amely fegyelmet, erőt és harci szellemet fejleszt.', 'A Kyokushin teljes kontaktos, de az első órád csak kondi és alapok — teljesen kontaktmentes.', 'Karate gi vagy kényelmes sportruha az első alkalomra.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '10', 'Octagon Fight Center', '{"MMA","BJJ"}', 'Könyves Kálmán körút 48, Budapest, 1097',
  47.4762, 19.0823, 'A dedicated combat sports facility with a full-size octagon cage. Professional-level training for serious competitors.', 'https://example.com/octagon',
  '{"competition-team","professional-coaches","hard-training"}', 'Serious training environment. Free trial class available — come and see if it fits your goals.', 'Shorts and rash guard for BJJ. MMA gloves and shin guards for MMA classes.',
  'high', '[{"day":"Monday","time":"19:30"},{"day":"Tuesday","time":"19:30"},{"day":"Thursday","time":"19:30"},{"day":"Saturday","time":"11:00"}]'::jsonb, 9,
  '+36 20 296 4555', 'octagonfightcenter@example.com', 'https://facebook.com/octagonfightcenter', 'https://instagram.com/octagonfightcenter',
  20000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('10', 'hu', 'Küzdősportokra dedikált létesítmény teljes méretű oktagonnal. Profi szintű edzés komoly versenyzőknek.', 'Komoly edzési környezet. Ingyenes próbaóra elérhető — nézd meg, hogy illik-e hozzád.', 'Rövidnadrág és rash guard BJJ-hez. MMA kesztyű és sípcsontvédő MMA órákhoz.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '11', 'Sparta Boxing Academy', '{"Boxing"}', 'Árpád út 59, Budapest, 1134',
  47.5234, 19.0689, 'Youth-focused boxing academy producing regional and national champions. Programs available for ages 8 and up.', 'https://example.com/sparta',
  '{"kids-classes","beginner-friendly","friendly-community"}', 'Youth-first gym. All ages welcome. First class is completely free — no commitment.', 'Comfortable clothes. Hand wraps and gloves available to borrow.',
  'medium', '[{"day":"Monday","time":"17:00"},{"day":"Wednesday","time":"17:00"},{"day":"Friday","time":"17:00"},{"day":"Saturday","time":"09:30"}]'::jsonb, 13,
  '+36 30 625 5145', 'spartaboxingacademy@example.com', 'https://facebook.com/spartaboxingacademy', 'https://instagram.com/spartaboxingacademy',
  16500, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('11', 'hu', 'Fiatalokra fókuszáló bokszakadémia, amely regionális és országos bajnokokat nevel. Programok 8 éves kortól.', 'Elsősorban fiatalokra épülő terem, de minden korosztályt szívesen látunk. Az első óra teljesen ingyenes, kötelezettség nélkül.', 'Kényelmes ruha. Kéztekercs és kesztyű kölcsönözhető.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '12', 'Cobra BJJ & Submission Wrestling', '{"BJJ"}', 'Nagymező utca 22, Budapest, 1065',
  47.5041, 19.0602, 'Focuses exclusively on BJJ and submission grappling. Small class sizes ensure personalized coaching.', 'https://example.com/cobra',
  '{"open-mat","professional-coaches","friendly-community"}', 'Small class sizes mean personal attention from day one. Bring a good attitude — we''ll handle the rest.', 'Rash guard or t-shirt and shorts. Gi available to borrow for the first session.',
  'medium', '[{"day":"Tuesday","time":"19:00"},{"day":"Thursday","time":"19:00"},{"day":"Saturday","time":"10:00"},{"day":"Sunday","time":"10:00"}]'::jsonb, 6,
  '+36 70 982 3880', 'cobrabjjsubmissionwrestling@example.com', 'https://facebook.com/cobrabjjsubmissionwrestling', 'https://instagram.com/cobrabjjsubmissionwrestling',
  16500, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('12', 'hu', 'Kizárólag BJJ-re és fogásharcra (submission wrestling) fókuszál. A kis csoportlétszám személyre szabott oktatást biztosít.', 'A kis csoportlétszám az első naptól kezdve személyes odafigyelést jelent. Hozz jó hozzáállást — a többit intézzük.', 'Rash guard vagy póló és rövidnadrág. Gi kölcsönözhető az első alkalomra.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '13', 'Ferencváros Küzdősport Klub', '{"Boxing","Karate","MMA"}', 'Mester utca 53, Budapest, 1095',
  47.4799, 19.0712, 'A community-based sports club in the heart of Ferencváros, offering boxing, karate, and MMA for locals of all backgrounds.', 'https://example.com/fkk',
  '{"beginner-friendly","kids-classes","friendly-community","women-friendly"}', 'Community club open to everyone. Relaxed atmosphere, zero judgment. Just show up.', 'Any comfortable sportswear. All equipment available to borrow.',
  'low', '[{"day":"Monday","time":"18:00"},{"day":"Wednesday","time":"18:00"},{"day":"Friday","time":"18:00"},{"day":"Saturday","time":"10:00"}]'::jsonb, 9,
  '+36 70 990 2460', 'ferencvaroskuzdosportklub@example.com', 'https://facebook.com/ferencvaroskuzdosportklub', 'https://instagram.com/ferencvaroskuzdosportklub',
  10500, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('13', 'hu', 'Közösségi sportklub Ferencváros szívében, bokszal, karatéval és MMA-val, mindenféle háttérrel rendelkező helyieknek.', 'Nyitott közösségi klub, mindenkinek. Laza hangulat, teljes elfogadás. Csak gyere el.', 'Bármilyen kényelmes sportruha. Minden felszerelés kölcsönözhető.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '14', 'Buda Combat Sports', '{"Muay Thai","MMA"}', 'Retek utca 12, Budapest, 1024',
  47.5109, 19.0261, 'Buda''s go-to gym for Muay Thai and MMA. Emphasizes fitness and self-defense alongside competitive training.', 'https://example.com/budacombat',
  '{"beginner-friendly","women-friendly","friendly-community"}', 'Strong self-defense focus. Dedicated women''s class every Wednesday evening — a safe and empowering space.', 'Sports clothes. Boxing wraps and gloves available to borrow.',
  'medium', '[{"day":"Monday","time":"18:30"},{"day":"Wednesday","time":"18:30"},{"day":"Thursday","time":"18:30"},{"day":"Saturday","time":"10:00"}]'::jsonb, 2,
  '+36 30 495 9978', 'budacombatsports@example.com', 'https://facebook.com/budacombatsports', 'https://instagram.com/budacombatsports',
  15000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('14', 'hu', 'Buda vezető terme thai bokszhoz és MMA-hoz. Kondíciót és önvédelmet hangsúlyoz a versenyfelkészítés mellett.', 'Erős önvédelmi fókusz. Külön női óra minden szerda este — biztonságos és önbizalmat adó közeg.', 'Sportruha. Bokszpólya és kesztyű kölcsönözhető.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '15', 'Grappling House', '{"BJJ","MMA"}', 'Hungária körút 77, Budapest, 1143',
  47.5039, 19.1019, 'Premier grappling facility offering BJJ and wrestling-based MMA. Home of the Budapest Grappling Open tournament.', 'https://example.com/grapplinghouse',
  '{"open-mat","competition-team","professional-coaches"}', 'Home of the Budapest Grappling Open. Serious competitors welcome — but all levels are trained here.', 'Rash guard and shorts for no-gi; gi for BJJ classes. Both available to borrow for a first visit.',
  'high', '[{"day":"Monday","time":"19:00"},{"day":"Tuesday","time":"19:00"},{"day":"Wednesday","time":"19:00"},{"day":"Thursday","time":"19:00"},{"day":"Saturday","time":"11:00"},{"day":"Sunday","time":"11:00"}]'::jsonb, 14,
  '+36 20 233 9140', 'grapplinghouse@example.com', 'https://facebook.com/grapplinghouse', 'https://instagram.com/grapplinghouse',
  22000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('15', 'hu', 'Vezető fogásharc-létesítmény BJJ-vel és birkózás-alapú MMA-val. A Budapest Grappling Open verseny otthona.', 'A Budapest Grappling Open otthona. Komoly versenyzőket is várunk — de minden szintet edzünk.', 'Rash guard és rövidnadrág no-gi-hoz; gi a BJJ órákhoz. Mindkettő kölcsönözhető az első alkalomra.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '16', 'Angyalföld Boxing Club', '{"Boxing"}', 'Szegedi út 17, Budapest, 1139',
  47.5323, 19.0776, 'A storied boxing club in District XIII with over 40 years of history producing Olympic-level talent.', 'https://example.com/angyal',
  '{"competition-team","professional-coaches","hard-training"}', 'A legendary club with high standards. Dedicated beginner program gets you ready at your own pace.', 'Hand wraps and boxing gloves. Available at the gym store.',
  'high', '[{"day":"Monday","time":"17:00"},{"day":"Tuesday","time":"17:00"},{"day":"Wednesday","time":"17:00"},{"day":"Thursday","time":"17:00"},{"day":"Friday","time":"17:00"}]'::jsonb, 13,
  '+36 20 142 9336', 'angyalfoldboxingclub@example.com', 'https://facebook.com/angyalfoldboxingclub', 'https://instagram.com/angyalfoldboxingclub',
  22000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('16', 'hu', 'Legendás bokszklub a XIII. kerületben, 40 éves múlttal és olimpiai szintű tehetségek nevelésével.', 'Legendás klub, magas elvárásokkal. Külön kezdő program segít saját tempódban felkészülni.', 'Kéztekercs és bokszkesztyű. Kapható a klub boltjában.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '17', 'Zuglói Karate Dojo', '{"Karate"}', 'Thököly út 145, Budapest, 1146',
  47.5119, 19.1088, 'Traditional Shotokan karate dojo in Zugló. Great for families and children, with a structured grading system.', 'https://example.com/zuglo',
  '{"beginner-friendly","kids-classes","friendly-community"}', 'Perfect for families. Children''s and adult classes run simultaneously — parents and kids can train together.', 'Comfortable clothes. White karate gi recommended after the first month.',
  'low', '[{"day":"Tuesday","time":"17:00"},{"day":"Thursday","time":"17:00"},{"day":"Saturday","time":"10:00"}]'::jsonb, 14,
  '+36 20 385 6566', 'zugloikaratedojo@example.com', 'https://facebook.com/zugloikaratedojo', 'https://instagram.com/zugloikaratedojo',
  13000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('17', 'hu', 'Hagyományos Shotokan karate dojo Zuglóban. Kiváló családoknak és gyerekeknek, strukturált övvizsga-rendszerrel.', 'Tökéletes családoknak. Gyerek- és felnőttórák egyszerre futnak — szülő és gyerek együtt edzhet.', 'Kényelmes ruha. Fehér karate gi ajánlott az első hónap után.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '18', 'Kelenföld Fight Academy', '{"Muay Thai","BJJ","Boxing"}', 'Kelenföldi út 30, Budapest, 1119',
  47.4612, 18.9987, 'A modern facility in south-west Buda offering Muay Thai, BJJ, and boxing classes throughout the day.', 'https://example.com/kelenfold',
  '{"beginner-friendly","women-friendly","open-mat"}', 'Morning and evening classes available — perfect if you have a busy schedule. Full equipment rental on site.', 'Sports clothes for the first class. The gym has full equipment rental for all disciplines.',
  'medium', '[{"day":"Monday","time":"07:00"},{"day":"Monday","time":"19:00"},{"day":"Wednesday","time":"07:00"},{"day":"Wednesday","time":"19:00"},{"day":"Friday","time":"07:00"},{"day":"Friday","time":"19:00"},{"day":"Saturday","time":"10:00"}]'::jsonb, 11,
  '+36 30 493 2860', 'kelenfoldfightacademy@example.com', 'https://facebook.com/kelenfoldfightacademy', 'https://instagram.com/kelenfoldfightacademy',
  18000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('18', 'hu', 'Modern létesítmény Dél-Budán, thai boksz, BJJ és boksz órákkal a nap folyamán.', 'Délelőtti és esti órák is elérhetők — tökéletes elfoglalt napirendhez. Teljes felszerelés-bérlés helyben.', 'Sportruha az első órára. A terem minden diszciplínához biztosít bérelhető felszerelést.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '19', 'Óbuda Martial Arts Club', '{"Karate","BJJ"}', 'Lajos utca 78, Budapest, 1036',
  47.5352, 19.0401, 'A friendly dojo in Óbuda teaching Karate and BJJ to children and adults. Strong focus on respect and discipline.', 'https://example.com/obuda',
  '{"beginner-friendly","kids-classes","friendly-community"}', 'Strong focus on respect and discipline. Great first martial arts experience for both kids and adults.', 'Comfortable clothes. Karate gi required after the first grading exam.',
  'low', '[{"day":"Monday","time":"17:30"},{"day":"Wednesday","time":"17:30"},{"day":"Friday","time":"17:30"}]'::jsonb, 3,
  '+36 20 238 1493', 'obudamartialartsclub@example.com', 'https://facebook.com/obudamartialartsclub', 'https://instagram.com/obudamartialartsclub',
  10000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('19', 'hu', 'Barátságos dojo Óbudán, karatét és BJJ-t oktat gyerekeknek és felnőtteknek. Erős tisztelet- és fegyelem-fókusz.', 'Erős tisztelet- és fegyelem-fókusz. Remek első harcművészeti élmény gyerekeknek és felnőtteknek egyaránt.', 'Kényelmes ruha. Karate gi az első övvizsga után kötelező.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '20', 'Pesterzsébet Fight Gym', '{"MMA","Boxing"}', 'Kossuth Lajos utca 93, Budapest, 1204',
  47.4221, 19.0812, 'Affordable MMA and boxing gym in District XX. Open evenings and weekends for working professionals.', 'https://example.com/pesterzsebet',
  '{"beginner-friendly","friendly-community"}', 'Affordable and no-fuss. Evening classes designed around working schedules. No prior experience needed.', 'Comfortable sports clothes. Basic equipment available to borrow.',
  'medium', '[{"day":"Tuesday","time":"19:00"},{"day":"Thursday","time":"19:00"},{"day":"Saturday","time":"10:00"}]'::jsonb, 20,
  '+36 30 521 7496', 'pesterzsebetfightgym@example.com', 'https://facebook.com/pesterzsebetfightgym', 'https://instagram.com/pesterzsebetfightgym',
  15000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('20', 'hu', 'Megfizethető MMA és boksz terem a XX. kerületben. Esténként és hétvégén nyitva dolgozóknak.', 'Megfizethető és egyszerű. Esti órák a munkaidőhöz igazítva. Nem szükséges előzetes tapasztalat.', 'Kényelmes sportruha. Alapfelszerelés kölcsönözhető.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '21', 'Champion Muay Thai Gym', '{"Muay Thai","Boxing"}', 'Dózsa György út 41, Budapest, 1071',
  47.5123, 19.0731, 'Established by a former Thai boxing champion, this gym offers authentic Muay Thai conditioning and technique classes.', 'https://example.com/champion',
  '{"professional-coaches","competition-team","hard-training"}', 'Founded by a champion — expect high-level technical coaching from day one. Conditioning-heavy first sessions.', 'Boxing wraps and shorts. Gloves and shin guards available to rent.',
  'high', '[{"day":"Monday","time":"18:00"},{"day":"Tuesday","time":"18:00"},{"day":"Thursday","time":"18:00"},{"day":"Friday","time":"18:00"},{"day":"Saturday","time":"10:00"}]'::jsonb, 7,
  '+36 70 776 8765', 'championmuaythaigym@example.com', 'https://facebook.com/championmuaythaigym', 'https://instagram.com/championmuaythaigym',
  19000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('21', 'hu', 'Egy egykori thai bajnok alapította; a terem autentikus thai box kondicionálást és technikaoktatást kínál.', 'Bajnok alapította — magas szintű technikai oktatás az első naptól. Az első alkalmak kondíció-hangsúlyosak.', 'Bokszpólya és rövidnadrág. Kesztyű és sípcsontvédő bérelhető.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '22', 'Újpest Küzdősport', '{"Karate","Muay Thai"}', 'István út 14, Budapest, 1042',
  47.5512, 19.0763, 'Versatile martial arts school in District IV, known for its passionate community and dedicated coaching staff.', 'https://example.com/ujpest',
  '{"friendly-community","beginner-friendly","women-friendly"}', 'Passionate coaching staff and welcoming atmosphere. Free trial class for all new members.', 'Comfortable sportswear for the trial. Equipment list provided after sign-up.',
  'medium', '[{"day":"Monday","time":"18:00"},{"day":"Wednesday","time":"18:00"},{"day":"Friday","time":"18:00"}]'::jsonb, 4,
  '+36 30 453 2931', 'ujpestkuzdosport@example.com', 'https://facebook.com/ujpestkuzdosport', 'https://instagram.com/ujpestkuzdosport',
  15500, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('22', 'hu', 'Sokoldalú harcművészeti iskola a IV. kerületben, elkötelezett közösségéről és odaadó oktatói gárdájáról ismert.', 'Elkötelezett edzői gárda és befogadó hangulat. Ingyenes próbaóra minden új tagnak.', 'Kényelmes sportruha a próbaórára. Felszereléslista regisztráció után.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '23', 'Ground Zero BJJ Academy', '{"BJJ"}', 'Soroksári út 48, Budapest, 1095',
  47.4701, 19.0678, 'A pure BJJ academy with black belt instructors and competitive teams at the national and international level.', 'https://example.com/groundzero',
  '{"competition-team","open-mat","professional-coaches"}', 'Black belt instructors with international competition experience. Beginners placed in dedicated fundamentals program.', 'BJJ gi or rash guard + shorts for no-gi classes. Available to borrow for a first session.',
  'high', '[{"day":"Monday","time":"19:00"},{"day":"Wednesday","time":"19:00"},{"day":"Friday","time":"19:00"},{"day":"Saturday","time":"11:00"},{"day":"Sunday","time":"11:00"}]'::jsonb, 9,
  '+36 30 659 5948', 'groundzerobjjacademy@example.com', 'https://facebook.com/groundzerobjjacademy', 'https://instagram.com/groundzerobjjacademy',
  18000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('23', 'hu', 'Tiszta BJJ akadémia fekete öves oktatókkal és országos, nemzetközi szinten versenyző csapatokkal.', 'Fekete öves oktatók nemzetközi versenytapasztalattal. A kezdők külön alapozó programba kerülnek.', 'BJJ gi vagy rash guard + rövidnadrág no-gi órákhoz. Az első alkalomra kölcsönözhető.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '24', 'Kispest Combat Club', '{"Boxing","MMA","Muay Thai"}', 'Határ út 5, Budapest, 1191',
  47.4478, 19.1012, 'A full-service combat sports club in District XIX offering boxing, Muay Thai, and MMA to competitors and fitness enthusiasts.', 'https://example.com/kispest',
  '{"beginner-friendly","friendly-community","open-mat"}', 'Full introductory program for every discipline. Come to the first class and we''ll set up the right path for you.', 'Sports clothes for the first class. Equipment list provided after your first session.',
  'medium', '[{"day":"Monday","time":"18:30"},{"day":"Wednesday","time":"18:30"},{"day":"Thursday","time":"18:30"},{"day":"Saturday","time":"10:00"}]'::jsonb, 19,
  '+36 30 577 4411', 'kispestcombatclub@example.com', 'https://facebook.com/kispestcombatclub', 'https://instagram.com/kispestcombatclub',
  17000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('24', 'hu', 'Teljes körű küzdősport klub a XIX. kerületben, bokszal, thai boksszal és MMA-val versenyzőknek és fitneszrajongóknak.', 'Teljes bevezető program minden diszciplínához. Gyere az első órára, és összeállítjuk a neked való utat.', 'Sportruha az első órára. Felszereléslista az első alkalom után.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '25', 'Pasarét Karate & Fitness', '{"Karate"}', 'Pasaréti út 8, Budapest, 1026',
  47.5213, 18.9978, 'A welcoming karate school in the hills of Buda, combining traditional martial arts with modern fitness methods.', 'https://example.com/pasaret',
  '{"beginner-friendly","women-friendly","friendly-community"}', 'Very welcoming atmosphere. Combined karate and fitness — great for those wanting both discipline and a workout.', 'Gym clothes. Karate gi is optional and can be purchased later.',
  'low', '[{"day":"Tuesday","time":"18:00"},{"day":"Thursday","time":"18:00"},{"day":"Saturday","time":"09:30"}]'::jsonb, 2,
  '+36 30 494 0665', 'pasaretkaratefitness@example.com', 'https://facebook.com/pasaretkaratefitness', 'https://instagram.com/pasaretkaratefitness',
  10000, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('25', 'hu', 'Barátságos karate iskola a budai hegyekben, amely a hagyományos harcművészetet modern fitnesszel ötvözi.', 'Nagyon barátságos hangulat. Karate és fitnesz egyben — remek azoknak, akik fegyelmet és edzést egyszerre keresnek.', 'Sportruha. A karate gi opcionális, később is beszerezhető.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '26', 'Józsefváros MMA Factory', '{"MMA","BJJ","Boxing"}', 'Baross utca 120, Budapest, 1082',
  47.4897, 19.0789, 'A no-nonsense MMA gym in District VIII with a reputation for producing serious fighters. Daily open mat included with membership.', 'https://example.com/jvmma',
  '{"hard-training","competition-team","open-mat"}', 'Serious and committed training environment. Daily open mat included. Come ready to work.', 'Full MMA gear required from week 2. Available to purchase on site or borrow for the first session.',
  'high', '[{"day":"Monday","time":"19:30"},{"day":"Tuesday","time":"19:30"},{"day":"Wednesday","time":"19:30"},{"day":"Thursday","time":"19:30"},{"day":"Friday","time":"19:30"},{"day":"Saturday","time":"11:00"}]'::jsonb, 8,
  '+36 30 442 1664', 'jozsefvarosmmafactory@example.com', 'https://facebook.com/jozsefvarosmmafactory', 'https://instagram.com/jozsefvarosmmafactory',
  19500, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('26', 'hu', 'Kompromisszumok nélküli MMA terem a VIII. kerületben, komoly versenyzőket nevelő hírnévvel. Napi open mat a tagságban.', 'Komoly, elkötelezett edzési környezet. Napi open mat is jár a tagsághoz. Gyere munkára készen.', 'Teljes MMA felszerelés a 2. héttől kötelező. Helyben vásárolható vagy kölcsönözhető az első alkalomra.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  '27', 'Budapest Muay Thai Center', '{"Muay Thai","MMA"}', 'Thaly Kálmán utca 15, Budapest, 1096',
  47.4766, 19.0615, 'Specializing in Muay Thai and MMA crossover training. Weekly seminars by visiting instructors from Thailand and the US.', 'https://example.com/bmtc',
  '{"professional-coaches","beginner-friendly","friendly-community"}', 'Weekly guest seminars from international coaches. Beginners are integrated smoothly into regular classes.', 'Shorts and t-shirt. Gloves and Thai pads available to borrow.',
  'medium', '[{"day":"Monday","time":"18:00"},{"day":"Wednesday","time":"18:00"},{"day":"Friday","time":"18:00"},{"day":"Saturday","time":"10:00"}]'::jsonb, 9,
  '+36 70 754 4528', 'budapestmuaythaicenter@example.com', 'https://facebook.com/budapestmuaythaicenter', 'https://instagram.com/budapestmuaythaicenter',
  15500, 'Monthly pass, per-class options may be available — ask the gym.', true, false,
  null
)
on conflict (id) do nothing;
insert into gym_translations (gym_id, lang, description, first_training_info, equipment_needed, price_note)
values ('27', 'hu', 'Thai boksz és MMA crossover edzésre specializálódott. Heti szemináriumok vendégoktatókkal Thaiföldről és az USA-ból.', 'Heti vendégszemináriumok nemzetközi edzőktől. A kezdők zökkenőmentesen illeszkednek a rendes órákba.', 'Rövidnadrág és póló. Kesztyű és thai pad kölcsönözhető.', 'Havi bérlet, alkalmankénti fizetés is lehetséges — kérdezd a klubot.')
on conflict (gym_id, lang) do nothing;

-- ─────────────────────────── Real, researched gyms ───────────────────────────

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  'r1', 'Budapesti Honvéd Sportegyesület – Karate szakosztály', '{"Karate"}', '1134 Budapest, Dózsa György út 53.',
  47.5227184, 19.0709076, null, 'https://honved.hu/karate/',
  null, null, null,
  null, null, null,
  '+36 20 399 6572', 'karate@honved.hu', null, null,
  null, null, false, false,
  'https://honved.hu/karate/'
)
on conflict (id) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  'r2', 'Rákosmenti Karate Sportegyesület (RKSE)', '{"Karate"}', '1173 Budapest, Pesti út 195.',
  47.4781881, 19.2606367, null, 'https://karateoktatas.eu/',
  null, null, null,
  null, null, null,
  '+36 30 646 8678', 'info@karate-do.hu', null, null,
  null, null, false, false,
  'https://karateoktatas.eu/'
)
on conflict (id) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  'r3', 'Gastroyal Karate Sportegyesület', '{"Karate"}', '1149 Budapest, Fráter György u. 31. II/7.',
  47.510616, 19.1190242, null, 'https://gastroyal.tagdij.com/',
  null, null, null,
  null, null, null,
  '+36 30 203 4008', 'gastroyal@karatezuglo.hu', null, null,
  null, null, false, false,
  'https://gastroyal.tagdij.com/contactus'
)
on conflict (id) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  'r4', 'Tűzmadár Sportegyesület', '{"Karate"}', '1182 Budapest, Hargita tér 14.',
  47.429943, 19.2065984, null, 'https://www.tuzmadarse.hu/',
  null, null, null,
  null, null, null,
  '+36 70 596 3367', 'info@tuzmadarse.hu', null, null,
  null, null, false, false,
  'https://www.tuzmadarse.hu/node/1604'
)
on conflict (id) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  'r5', 'OSU Kyokushin Karate', '{"Karate"}', '1132 Budapest, Victor Hugo utca 6.',
  47.5174265, 19.0586518, null, 'https://osu.hu/',
  null, null, null,
  null, null, null,
  null, 'honkyokushin@yahoo.com', null, null,
  null, null, false, false,
  'https://osu.hu/'
)
on conflict (id) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  'r6', 'Budai XI Karate Sportegyesület', '{"Karate"}', '1119 Budapest, Hadak útja 6.',
  47.4617938, 19.027878, null, 'https://buxikarate.hu/',
  null, null, null,
  null, null, null,
  null, null, null, null,
  null, null, false, false,
  'https://buxikarate.hu/budapest/'
)
on conflict (id) do nothing;

insert into gyms (
  id, name, sport, address, lat, lng, description, website, tags,
  first_training_info, equipment_needed, intensity_level, schedule,
  district, phone, email, facebook, instagram, price_from, price_note,
  is_demo, claimed, source_url
) values (
  'r7', 'Seishin Sportegyesület (WKB)', '{"Karate"}', '1203 Budapest, Lajtha László u. 2.',
  47.4431842, 19.0963193, null, 'https://www.seishindojo.hu/',
  null, null, null,
  null, null, null,
  null, null, null, null,
  null, null, false, false,
  'https://www.seishindojo.hu/'
)
on conflict (id) do nothing;

