// Real, researched Budapest karate clubs (address + email verified via public
// sources — see README/commit message for the source links). Only verified
// facts are included; nothing here is invented. Fields we couldn't verify
// (schedule, price, description, tags, intensity) are left null — the gym
// itself fills those in once it claims the listing.
module.exports = [
  {
    id: 'r1',
    name: 'Budapesti Honvéd Sportegyesület – Karate szakosztály',
    sport: ['Karate'],
    address: '1134 Budapest, Dózsa György út 53.',
    lat: 47.5227184,
    lng: 19.0709076,
    website: 'https://honved.hu/karate/',
    email: 'karate@honved.hu',
    phone: '+36 20 399 6572',
    sourceUrl: 'https://honved.hu/karate/',
  },
  {
    id: 'r2',
    name: 'Rákosmenti Karate Sportegyesület (RKSE)',
    sport: ['Karate'],
    address: '1173 Budapest, Pesti út 195.',
    lat: 47.4781881,
    lng: 19.2606367,
    website: 'https://karateoktatas.eu/',
    email: 'info@karate-do.hu',
    phone: '+36 30 646 8678',
    sourceUrl: 'https://karateoktatas.eu/',
  },
  {
    id: 'r3',
    name: 'Gastroyal Karate Sportegyesület',
    sport: ['Karate'],
    address: '1149 Budapest, Fráter György u. 31. II/7.',
    lat: 47.5106160,
    lng: 19.1190242,
    website: 'https://gastroyal.tagdij.com/',
    email: 'gastroyal@karatezuglo.hu',
    phone: '+36 30 203 4008',
    sourceUrl: 'https://gastroyal.tagdij.com/contactus',
  },
  {
    id: 'r4',
    name: 'Tűzmadár Sportegyesület',
    sport: ['Karate'],
    address: '1182 Budapest, Hargita tér 14.',
    lat: 47.4299430,
    lng: 19.2065984,
    website: 'https://www.tuzmadarse.hu/',
    email: 'info@tuzmadarse.hu',
    phone: '+36 70 596 3367',
    sourceUrl: 'https://www.tuzmadarse.hu/node/1604',
  },
  {
    id: 'r5',
    name: 'OSU Kyokushin Karate',
    sport: ['Karate'],
    address: '1132 Budapest, Victor Hugo utca 6.',
    lat: 47.5174265,
    lng: 19.0586518,
    website: 'https://osu.hu/',
    email: 'honkyokushin@yahoo.com',
    phone: null,
    sourceUrl: 'https://osu.hu/',
  },
  {
    id: 'r6',
    name: 'Budai XI Karate Sportegyesület',
    sport: ['Karate'],
    address: '1119 Budapest, Hadak útja 6.',
    lat: 47.4617938,
    lng: 19.0278780,
    website: 'https://buxikarate.hu/',
    email: null, // protected on their site, couldn't extract
    phone: null,
    sourceUrl: 'https://buxikarate.hu/budapest/',
  },
  {
    id: 'r7',
    name: 'Seishin Sportegyesület (WKB)',
    sport: ['Karate'],
    address: '1203 Budapest, Lajtha László u. 2.',
    lat: 47.4431842,
    lng: 19.0963193,
    website: 'https://www.seishindojo.hu/',
    email: null, // protected on their site, couldn't extract
    phone: null,
    sourceUrl: 'https://www.seishindojo.hu/',
  },
];
